### PR TITLE
Array constructor wallet addresses, add limit

### PR DESCRIPTION
**Pull request by semaj**

### CODE REVIEW

**Comment by semaj** [comment]
@matthieu hey, added the limit option to a call and added the `Array` function to the wallet address calls - so you can send in one address or an array of them.

**Comment by matthieu** [comment]
Merged, thanks!

**Comment by semaj** [comment]
@matthieu any upcoming releases?

**Comment by matthieu** [comment]
Trying to. Contacted @simcap who's the owner on rubygems right now. Otherwise we may have to rename the gem...

**Comment by matthieu** [comment]
Actually never mind, going to set it to blockcypher-ruby anyway. Want to submit a pull request to add you guys in the author section?

**Comment by simcap** [comment]
Hi. I think there was some confusion @matthieu . But no worries. I am not the owner of this gem. Personally, I wrote a another Blockcypher ruby client though (https://github.com/simcap/blockcypher-client) mainly to not depend on the monolithic bitcoin-ruby when we only need a very small subset of functionalities from it. It is not finished and should depend only on the lighter bitcoin-keys (https://github.com/simcap/bitcoin-keys) I wrote as well

**Comment by matthieu** [comment]
Thanks for chiming in, yeah I realized the confusion only after.

How about integrating bitcoin-keys here instead?

**Pull request merged**
