### PR TITLE
add api token option to all calls, add unspentOnly to address details call

### PR DESCRIPTION
**Pull request by semaj**
The API documentation mentions an API token query parameter and unspentOnly qparam for address details. I added them to the Ruby client. 

also - hi from Gem! :)

@williamcoates @matthieu

### CODE REVIEW

**Comment by matthieu** [comment]
I just merged another pull requests introducing a dependency to rest_client. Can you just update the locked Gemfile?

Otherwise the pull request looks good, thanks! And hi Gem :-)

**Comment by semaj** [comment]
hey @matthieu will do.

Another question: what is the 'filter' property on webhook creation? Shouldn't that be 'event'?
Also, there isn't currently a way to add more properties to that json object, like 'confirmations'. 

Shall I make those two changes as well?

**Comment by matthieu** [comment]
hey @semaj, filter is deprecated. It used to be some expression that had the event type, address or hash, etc. Now it's just a JSON object with properties.

Please make those changes too. Thanks!

**Comment by semaj** [comment]
@matthieu added a few more things.

However, it looks like the changes you just merged into master do not have passing tests.

**Comment by matthieu** [comment]
Arf, you're right. Reverted the merge until tests are fixed. Is your branch ready to be merged?

**Comment by semaj** [comment]
@matthieu it is, however it looks like there are failing tests on master still - possibly unrelated to any PRs.

**Comment by matthieu** [comment]
@semaj merging your pull request as it should be neutral to those failures, I'll check those out independently. Thanks again!

**Pull request merged**
